### ISSUE TITLE
Standardize resource Naming/Tagging

### ISSUE THREAD

**Issue by AaronNBrock** [contino/tpgsi-terraform-demo#3]
There needs to be some standardization of the naming and tagging for each resource, following the best practices outlined [here](https://confluence.huit.harvard.edu/display/CLA/Cloud+Resource+Naming+Conventions?desktop=true&macroName=livesearch)

**Comment by dan-petty** [comment]
https://github.com/contino/tpgsi-terraform-demo/pull/4

**Comment by AaronNBrock** [comment]
Resolved with #4
